# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swmmVersion <- function() {
    .Call(`_swmm_swmmVersion`)
}

swmmRun <- function(inpFile, rptFile, outFile) {
    .Call(`_swmm_swmmRun`, inpFile, rptFile, outFile)
}

OpenSwmmOutFile <- function(outFile) {
    .Call(`_swmm_OpenSwmmOutFile`, outFile)
}

GetSwmmResult <- function(iType, iIndex, vIndex) {
    .Call(`_swmm_GetSwmmResult`, iType, iIndex, vIndex)
}

GetSwmmTimes <- function() {
    .Call(`_swmm_GetSwmmTimes`)
}

CloseSwmmOutFile <- function() {
    .Call(`_swmm_CloseSwmmOutFile`)
}

