
#' Read SWMM out files in long format
#'
#' @param path A path to a .out file generated by [swmm_run()].
#' @param element_type One of 'subcatchments', 'links', 'nodes', or 'system',
#'   or `NULL` to read everything.
#' @param variable See [swmm_read_variables()] for choices,
#'   or `NULL` to read everything.
#' @param object_name An object name or `NULL` to read everything.
#'
#' @return A data frame
#' @export
#'
#' @importFrom rlang .data
swmm_read_out <- function(path, element_type = NULL, variable = NULL, object_name = NULL) {
  out_vars <- swmm_read_variables(path)

  if(!is.null(element_type)) {
    assert_that(is.character(element_type))
    out_vars <- out_vars[out_vars$element_type %in% element_type, ]
  }
  if(!is.null(variable)) {
    assert_that(is.character(variable))
    out_vars <- out_vars[out_vars$element_type %in% variable, ]
  }
  if(!is.null(object_name)) {
    assert_that(is.character(object_name))
    out_vars <- out_vars[out_vars$object_name %in% object_name, ]
  }

  indices <- out_vars[c("type_index", "variable_index", "object_index")]
  indices$path <- path

  out_vars$value <- purrr::pmap(indices, swmm_read_out_index)
  out_vars$step <- purrr::map(out_vars$value, seq_along)
  tidyr::unnest(out_vars, .data$value, .data$step)
}

#' Read .out file convenience functions
#'
#' @inheritParams swmm_read_out
#' @export
#'
swmm_read_variables <- function(path) {
  meta <- swmm_read_out_meta(path)

  variables <- rbind(
    out_variables[!grepl("pollutant", out_variables$variable), ],
    pollutant_variables(meta$pollutants$names)
  )

  objects <- object_variables(
    subcatchments = meta$subcatchments$names,
    links = meta$links$names,
    nodes = meta$nodes$names
  )

  merge(variables, objects, all = FALSE)
}

#' @rdname swmm_read_variables
#' @export
swmm_read_subcatchments <- function(path, variable = NULL, object_name = NULL) {
  swmm_read_single_type(path, "subcatchments", variable = variable, object_name = object_name)
}

#' @rdname swmm_read_variables
#' @export
swmm_read_links <- function(path, variable = NULL, object_name = NULL) {
  swmm_read_single_type(path, "links", variable = variable, object_name = object_name)
}

#' @rdname swmm_read_variables
#' @export
swmm_read_nodes <- function(path, variable = NULL, object_name = NULL) {
  swmm_read_single_type(path, "nodes", variable = variable, object_name = object_name)
}

#' @rdname swmm_read_variables
#' @export
swmm_read_system <- function(path, variable = NULL, object_name = NULL) {
  swmm_read_single_type(path, "system", variable = variable, object_name = object_name)
}

swmm_read_single_type <- function(path, element_type, variable, object_name) {
  out <- swmm_read_out(path, element_type, variable = variable, object_name = object_name)
  tidyr::spread(
    out[c("object_name", "variable", "step", "value")],
    key = .data$variable,
    value = .data$value
  )
}

swmm_read_out_index <- function(path, type_index, variable_index, object_index) {
  assert_that(is.character(path), length(path) == 1, file.exists(path))
  on.exit(CloseSwmmOutFile())
  OpenSwmmOutFile(path)
  GetSwmmResult(type_index, object_index, variable_index)
}

swmm_read_out_meta <- function(path) {
  assert_that(is.character(path), length(path) == 1, file.exists(path))
  on.exit(CloseSwmmOutFile())
  OpenSwmmOutFile(path)
}

pollutant_variables <- function(pollutant_names = character(0)) {
  if(length(pollutant_names) == 0) return(out_variables[integer(0), ])
  pollutant_vars_base <- out_variables[grepl("pollutant", out_variables$variable), ]

  pollutant_vars_list <- lapply(seq_along(pollutant_names), function(i) {
    pollutant_vars <- pollutant_vars_base
    pollutant_vars$variable <- sprintf(pollutant_vars$variable, pollutant_names[i])
    pollutant_vars$variable_name <- sprintf(pollutant_vars$variable_name, pollutant_names[i])
    pollutant_vars$variable_index <- pollutant_vars$variable_index + i - 1
    pollutant_vars
  })

  do.call(rbind, pollutant_vars_list)
}

object_variables <- function(subcatchments = character(0), links = character(0), nodes = character(0)) {
  assert_that(is.character(subcatchments), is.character(links), is.character(nodes))
  args <- list(subcatchments = subcatchments, links = links, nodes = nodes, system = "system")
  vars <- Map(object_variables_single, names(args), args)
  vars_tbl <- do.call(rbind, vars)
  rownames(vars_tbl) <- NULL
  vars_tbl
}

object_variables_single <- function(element_type, object_name) {
  if(length(element_type) == 0 || length(object_name) == 0) {
    return(
      data.frame(
        element_type = character(0),
        object_name = character(0),
        object_index = integer(0),
        stringsAsFactors = FALSE
      )
    )
  }

  df <- data.frame(element_type = element_type, object_name = object_name, stringsAsFactors = FALSE)
  df$object_index <- seq_along(object_name) - 1
  df
}
